### ISSUE TITLE
nginx log files have wrong SELinux label on RHEL 8.6

### ISSUE THREAD

**Issue by benformosa** [Alfresco/alfresco-ansible-deployment#347]
#### Bug description

I'm not sure how this situation occurred, but after updating my system to RHEL 8.6, I was unable to start nginx due to incorrect SELinux labels on `/var/log/alfresco/nginx.alfresco.access.log` and `/var/log/alfresco/nginx.alfresco.error.log`.

My solution was to add an fcontext mapping to change the type to `http_log_t`:
```bash
sudo semanage fcontext --add --type 'httpd_log_t' '/var/log/alfresco/nginx.*'
sudo restorecon -v /var/log/alfresco/nginx.alfresco.{access,error}.log
```

#### Target OS

RHEL 8.6

#### Ansible error

N/A

#### Proposal

Include a task to add an fcontext mapping, e.g.

````yaml
- name: Allow nginx to write log files to /var/log/alfresco
  community.general.sefcontext:
    target: '/var/log/alfresco/nginx.*'
    setype: httpd_log_t
    state: present

- name: Apply new SELinux file context to filesystem
  ansible.builtin.command: restorecon -iv /var/log/alfresco/nginx.*
````
